services:
    postgres:
        container_name: db-api
        environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        image: 'postgres:9.6'
