services:
    postgres:
        container_name: db-api
        environment:
            - POSTGRES_PASSWORD=passdb
            - POSTGRES_USER=userdb
            - POSTGRES_DB=namedb
        ports:
            - '5432:5432'
        image: 'postgres:9.6'
