services:
    postgres:
        container_name: db-api
        environment:
            - POSTGRES_PASSWORD=passdb
            - POSTGRES_USER=userdb
            - POSTGRES_DB=namedb
        ports:
            - '5432:5432'
        volumes:
            - '$HOME/docker/volumes/postgres-db-api:/var/lib/postgresql/data'
        image: 'postgres:9.6'
